### ISSUE TITLE
out of memory error when using my own data

### ISSUE THREAD

**Issue by xiaoqianjia** [jhoffman/cycada_release#12]
Hi
I have one question. When I use my own data to do cyclegan_semantic model. I meet out of memory error. My image size is a little bigger, but I have resized them. I want to ask when you do the cyclegan_semantic to GTA-city image? Do you use same code as minst_svhn(which from Github)? Or when we use model to more complex dataset, we should adjust the code.
Thanks!

**Comment by zhou-rui1** [comment]
Hi, may I ask how to train my own dataset(with only images and labels)?
