### ISSUE TITLE
What resolution did you use to adapt between GTAV and Cityscapes?

### ISSUE THREAD

**Issue by IssamLaradji** [jhoffman/cycada_release#17]
Did you resize your images to 128 x 128 to make cyclegan work for GTAV -> Cityscapes?

**Comment by JamesChenChina** [comment]
For cycle-consistent image level adaptation, we followed the network architecture and hyperparameters
of CycleGAN(Zhu et al., 2017). All images were resized to have width of 1024 pixels while keeping
the aspect ratio, and the training was performed with randomly cropped patches of size 400 by 400.

according to https://arxiv.org/pdf/1711.03213.pdf

Is that info you want?

**Comment by jhoffman** [comment]
We followed the CycleGAN approach during image-space adaptation and used crops of size 768 during feature space adaptation see: https://github.com/jhoffman/cycada_release/blob/master/scripts/train_fcn_adda.sh
