### ISSUE TITLE
Links in README don't work

### ISSUE THREAD

**Issue by xyyue** [jhoffman/cycada_release#2]
First, thanks a lot for releasing the code!!!
One minor issue is that the links for the DRN models at the end of the README doesn't work anymore... Would you mind checking this? Thank you so much again!

**Comment by chihkuanyeh** [comment]
I am experiencing the same problem, would appreciate some help here.

**Comment by jzhuospark** [comment]
You can still download them from https://people.eecs.berkeley.edu/~jhoffman/cycada/

**Comment by mhusseinsh** [comment]
@jzhuospark sorry I have a question
So these are pretrained models on GTA dataset ?
what if I want to train on my own dataset ?

Any advice on how to get CyCADA running on my own dataset ?

**Comment by jhoffman** [comment]
The links have been updated and should now work again. Thanks for letting me know!

**Comment by mhusseinsh** [comment]
@jhoffman Hello Judy
Sorry for reopening the issue again.
I want to use cycada in training on image-to-image translation from simulation to real world domain (something like GTA to cityscape), but another dataset. Accordingly, I cannot use the pretrained model/weights that you provided in the links.
Do you have the semantic segmentation network, which you used in training GTA data, so I can adapt it for my simulation dataset also.
I already have the data labeled, with GT semantics

**Comment by xiaoqianjia** [comment]
I have same problem, how can we train a semantic segmentation network?

**Comment by jhoffman** [comment]
You can either initialize your model with the GTA weights or train the FCN. If you would prefer to finetune from the classification model you need to set pretrain=True and finetune=True to the DRN model and uncomment the code: https://github.com/jhoffman/cycada_release/blob/c414d9745f48c65d39ce6b63dc847f8fc96fa145/cycada/models/drn.py#L252

**Comment by nanditam1** [comment]
Hi, the links to pre-trained models are unavailable. Is there an alternate path? Thanks.

**Comment by remsto** [comment]
> Hi, the links to pre-trained models are unavailable. Is there an alternate path? Thanks.

Hi ! You can get the weights from here : http://dl.yf.io/drn/
