### ISSUE TITLE
What's the identity loss?

### ISSUE THREAD

**Issue by Luodian** [jhoffman/cycada_release#23]
@In your code, there's an identity loss, but I didn't find this part in paper~ 

Is it useful in your final improvement?

https://github.com/jhoffman/pytorch-CycleGAN-and-pix2pix/blob/e484612d83449d05024a7d5fd2e012be53faad85/models/cycle_gan_semantic_model.py#L136

**Comment by Luodian** [comment]
@jhoffman 
Hi~Prof. Hoffman,
I saw you didn't use the identity loss in your code, is it useful for semantic segmentation? May I know this lambda value in your final result model?
![image](https://user-images.githubusercontent.com/15847405/56882250-ab697f80-6a95-11e9-8aa2-b1d4c61cbe35.png)

**Comment by vicdxxx** [comment]
lambdaG is 10 times less than lambdaD， quote paper(Appendix):
 We weight the representation loss ten times less than the discriminator loss as a convienience since otherwise the discriminator did not learn a suitable model within a single epoch
