### ISSUE TITLE
Pretrained models for SVHN2MNIST

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [jhoffman/cycada_release#27]
Hi, 

I am interested in comparing the results of our own domain transfer algorithm with the results in your paper. 

Would it possible to get the successfully trained models for `svhn2mnist`, `mnist2usps` and the other alterations that you trained for getting the results ? That would enable me to run this code with the pretrained models and extract the results myself. 

Please let me know. 
Thanks in advance,

**Comment by jhoffman** [comment]
You should be able to run the scripts/train_adda.py using the downloaded transformed images for those two shifts to train those models.
