### ISSUE TITLE
Is your feature adaptation ADDA?

### ISSUE THREAD

**Issue by iamxiaoyubei** [jhoffman/cycada_release#28]
Hi! After reading your code, I think your feature adaptation（scripts/train_adda.py） is the ADDA method. Am I right? Besides, I found that you directly put the results of the entire network into ADDA instead of the feature extraction output. I am confused, is this still feature adaptation?

**Comment by jhoffman** [comment]
Yes, using feature adaptation on transformed images is a part of the method.
