### ISSUE TITLE
Only part of GTA images is used?

### ISSUE THREAD

**Issue by chentao2016** [jhoffman/cycada_release#29]
I download GTA as CityScapes images (16GB). But I only find 22061 rather than 24966 GTA images. Is there any selection strategy?

**Comment by Zhang-haotian** [comment]
> I download GTA as CityScapes images (16GB). But I only find 22061 rather than 24966 GTA images. Is there any selection strategy?

I am always trying to execute segmentation on biomedical image data, but following the author's instruction in Readme, I only download the data named 'cyclegta' which is looked like synthetic images conversed from GTA5 to Cityscapes. I was wondering that have you reproduced the author's performance on real-world data?  @chentao2016  🤨

**Comment by chentao2016** [comment]
@Zhang-haotian  I didn't try it. I just wanted to run my own code based on the transformed images.

**Comment by jhoffman** [comment]
These images correspond to the "train" set from the GTA dataset. If you download GTA it comes with a file called something like split.mat which specifies the splits.
