### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by engharat** [jhoffman/cycada_release#3]
Hi,
I would like to replicate the paper results ( SVHN->MNIST for example) but I just noticed that the test_cycada.sh script and the following test.py produce just the converted images and do not produce any accuracy at all. 
Could you suggest me how to operate in order to reproduce the numerical paper results? Should I write my own test function, testing the target dataset after a full training?

**Comment by jhoffman** [comment]
The accuracy is reported from the final model which performs feature adaptation. See scripts/train_adda.py for an example which trains directly with svhn -> mnist (feature adapt only) to include image adaptation as well use the dataset src='svhn2mnist' and point to the folder which is the output from image adaptation or directly download the relevant images here: https://eecs.berkeley.edu/~jhoffman/cycada/svhn2mnist/
