### ISSUE TITLE
Question about the novelty of CyCADA in the datasets with larger domain gap

### ISSUE THREAD

**Issue by AlanLuSun** [jhoffman/cycada_release#31]
After analyzing the code, I feel it just a combination of Cycle-GAN and ADDA and theoretically, the transfer performance should severely depend on the generation performance of fake source-like images. It would remain a question for the performance in the datasets with a little bit larger domain gap instead of simple handwritten digits.

**Comment by jhoffman** [comment]
This work brings together image space (building on CycleGAN but adding semantic consistency) and feature space (building on Adda and generalizing to semantic segmentation). You are correct that the effectiveness of the approach will depend on the difference between the domains. We experimented with GTA->cityscapes in addition to the digit experiments.
