### ISSUE TITLE
Code for GTA as CityScapes without segmentation

### ISSUE THREAD

**Issue by kpagels** [jhoffman/cycada_release#33]
Hi @jhoffman or other people,

I know you are busy, but I hope you have time to answer me.

I have tried to locate the code where you run a transfer of GTA to CityScapes? And not the Segmentation part of the code. Are you using the cycle_gan_segmantic model for this? And if so, did you change the structure of the netCLS etc? Did you actually release the code for the GTA to CityScapes? And can this be run without pretrained models?

My goal is to use it for my own data and here I don't have any pretrained models.

I hope you can help!

Thanks!

**Comment by jhoffman** [comment]
At the time of this release, GTA->cityscapes *image* translation was run using the CycleGAN code base linked within this repo. The output translated images are then input to our feature adaptation and segmentation code here.
