### ISSUE TITLE
No such file or directory: 'gta/cyclegta5/split.mat'

### ISSUE THREAD

**Issue by jzhuospark** [jhoffman/cycada_release#4]
I I download the gta images, put it under the cycada folder, and set data_dir to be 'gta/'.

I tried to run `bash scripts/train_fcn_adda.sh` and got this error:

`No such file or directory: 'gta/cyclegta5/split.mat'`

Could you please let me know where I can find the `split.mat`? Thanks!

**Comment by jhoffman** [comment]
This will be the same split.mat file which is released with GTA5.

**Comment by xiaoqianjia** [comment]
@jzhuospark  I met same problem. How do you solve it?

**Comment by didirus** [comment]
Same problem!

**Comment by iamxiaoyubei** [comment]
+1

**Comment by Bowenwu1** [comment]
Please read the website carefully.  https://download.visinf.tu-darmstadt.de/data/from_games/
![image](https://user-images.githubusercontent.com/16816766/62944529-751afa80-be0f-11e9-927b-c3f5c87cd790.png)

Download Link for split info is:
https://download.visinf.tu-darmstadt.de/data/from_games/code/read_mapping.zip

**Comment by iamxiaoyubei** [comment]
@Bowenwu1 Thank you!
