### ISSUE TITLE
Dataset download fail

### ISSUE THREAD

**Issue by mylife126** [jhoffman/cycada_release#40]
Dear authors,

I was trying to download the dataset such as "Mnist to UPS", but none of these dataset is still available. The link seems invalid. Would you please kindly provide us with the dataset to play around with your code? 

Thanks!

**Comment by zhe-juanz** [comment]
"Mnist to UPS" could be downloaded from https://www.dropbox.com/s/xjt8gzdfwlyugsg/mnist2usps.zip?dl=0

**Comment by ZHE-SAPI** [comment]
> Dear authors,
> 
> I was trying to download the dataset such as "Mnist to UPS", but none of these dataset is still available. The link seems invalid. Would you please kindly provide us with the dataset to play around with your code?
> 
> Thanks!

"Mnist to UPS" could be downloaded from https://www.dropbox.com/s/xjt8gzdfwlyugsg/mnist2usps.zip?dl=0
