### ISSUE TITLE
labels not found

### ISSUE THREAD

**Issue by chenxizi-c** [jhoffman/cycada_release#42]
In the file `cyclegta5.py` in folder data, there is
```
def __getitem__(self, index):
        id = self.ids[index]
        filename = '{:05d}.png'.format(id)
        img_path = os.path.join(self.root, 'images', filename)
        label_path = os.path.join(self.root, 'labels', filename)
```
but I can't find the labels file.
Could you please tell me where I can find it? Thanks!

**Comment by jhoffman** [comment]
Please find the label files and meta data in the original GTA dataset
