### ISSUE TITLE
unaligned_A_labeled file not found

### ISSUE THREAD

**Issue by Wanger-SJTU** [jhoffman/cycada_release#7]
In the file `__init__.py` in folder `data`, there is 

    elif opt.dataset_mode == 'unaligned_A_labeled':
        from data.unaligned_A_labeled_dataset import UnalignedALabeledDataset
        dataset = UnalignedALabeledDataset()

but there is not corresponding file found.  How could I prepare the dataset? thx.

**Comment by hankhaohao** [comment]
I also encountered the same problem，I don't know how to produce A_label file
